#%RAML 1.0 DataType
properties:
  apiName:
    type: string
    required: true
    example: test-api
  apiVersion:
    type: string
    required: true
    example: v1
  env:
    type: string
    required: true
    example: dev
  runtimeVersion:
    type: string
    required: true
    example: "4.3"
  startDate:
    type: string
    required: true
    example: 2021-05-25T04:40:35.463Z
  timeZone:
    type: string
    required: true
    example: UTC
  traceId:
    type: string
    required: true
    example: 7380a400-bd17-11eb-b638-027805932b52