#%RAML 1.0 DataType
properties:
  count:
    type: number
    required: true
    example: 25
  name:
    type: string
    required: true
    example: copy
  time:
    type: number
    required: true
    example: 555