#%RAML 1.0 DataType



properties:
  heapMaxSize: 
    type: number
    required: true
    example: 478150656
  heapCommitedSize:
    type: number
    required: true
    example: 478150656
  heapUsedSize:
    type: number
    required: true
    example: 478150656
  heapInitSize:
    type: number
    required: true
    example: 478150656