#%RAML 1.0 DataType


properties:
  startedThreadCount:
    type: number
    required: true
    example: 683
  peakThreads:
    type: number
    required: true
    example: 64

  threadCount:
    type: number
    required: true
    example: 63

  demonThreads:
    type: number
    required: true
    example: 19